SET SQL_SAFE_UPDATES = 0;
drop table if exists LOINC_EQUIV;
create table LOINC_EQUIV like LOINC_EQUIV_INPUT;
INSERT INTO LOINC_EQUIV SELECT * FROM LOINC_EQUIV_INPUT;
-- Create modified copies of columns before proceding.
ALTER TABLE LOINC_EQUIV ADD SYSTEM_REV TEXT;
UPDATE LOINC_EQUIV SET SYSTEM_REV = SYSTEM;
ALTER TABLE LOINC_EQUIV ADD METHOD_REV TEXT;
UPDATE LOINC_EQUIV SET METHOD_REV = METHOD_TYP;

ALTER TABLE LOINC_EQUIV ADD EQUIV_CLS TEXT;

UPDATE LOINC_EQUIV set METHOD_REV = '' where METHOD_REV not in ("IFCC", "JDS/JSCC", "Estimated");
UPDATE LOINC_EQUIV set SYSTEM_REV = 'Bld R' where COMPONENT in ("Deoxyhemoglobin/Hemoglobin.total");
UPDATE LOINC_EQUIV set SYSTEM_REV = 'Bld R or L' where SYSTEM in ("Bld", "BldA", "BldC", "BldV", "BldMV") and
   COMPONENT in ("Hemoglobin", "Hematocrit");

-- Cord blood
UPDATE LOINC_EQUIV set SYSTEM_REV = 'BldCo R or L' where SYSTEM in ("BldCo", "BldCoA", "BldCoV") and
   COMPONENT in ("Hemoglobin", "Hematocrit");
   
UPDATE LOINC_EQUIV set EQUIV_CLS=CONCAT(COMPONENT,"|",PROPERTY,"|",TIME_ASPCT,"|",SYSTEM_REV,"|",SCALE_TYP,"|",METHOD_REV);